"""baseline schema

Revision ID: 48b6c8479c7d
Revises: 
Create Date: 2026-09-09 14:26:21.379226
"""
from collections import defaultdict

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b6c8479c7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False, comment='动作类型'),
    sa.Column('actor_type', sa.String(length=16), server_default='user', nullable=False, comment='操作者类型：user/visitor/system'),
    sa.Column('actor_id', sa.String(length=64), nullable=True, comment='操作者标识（用户ID或访客ID）'),
    sa.Column('target', sa.String(length=64), nullable=True, comment='操作对象'),
    sa.Column('detail', sa.JSON(), nullable=True, comment='操作上下文（按需脱敏）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)

    op.create_table('schema_migrations',
    sa.Column('version', sa.String(length=64), nullable=False, comment='迁移版本名（如 birth_to_json_v1）'),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='应用时间'),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('shares',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID（FK users.id，登录态隔离）'),
    sa.Column('module', sa.String(length=32), nullable=False, comment='模块标识：tarot / bugua / dream'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='分享标题/关键词（如牌阵名、梦境主题）'),
    sa.Column('share_text', sa.String(length=4096), nullable=False, comment='分享文案'),
    sa.Column('image_url', sa.String(length=1024), nullable=True, comment='配图URL（CogView 生成，可能为空）'),
    sa.Column('image_prompt', sa.String(length=1024), nullable=True, comment='配图提示词（生成失败时为 None）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module', name='uq_shares_user_module')
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shares_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_user_id'), ['user_id'], unique=False)

    op.create_table('user_stash',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_key', sa.String(length=96), nullable=False, comment='身份键：user:{id} / visitor:{visitor_id}'),
    sa.Column('key', sa.String(length=128), nullable=False, comment='数据键（与前端 localStorage key 对齐）'),
    sa.Column('value', sa.Text(), nullable=False, comment='JSON 序列化的业务数据'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_key', 'key', name='uq_stash_owner_key')
    )
    with op.batch_alter_table('user_stash', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_stash_owner_key'), ['owner_key'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱（可选）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希（pbkdf2_sha256）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间戳（合规：账号注销走软删）'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('reports',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='登录用户ID（为空则为匿名访客）'),
    sa.Column('visitor_id', sa.String(length=64), nullable=False, comment='访客ID（匿名云存储标识 / 登录后保留作溯源）'),
    sa.Column('owner_type', sa.String(length=8), server_default='visitor', nullable=False, comment='数据归属：visitor=匿名 / user=登录用户'),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False, comment='排盘输入参数（出生信息/时辰/性别/问题）'),
    sa.Column('results', sa.JSON(), nullable=False, comment='各术数排盘结果快照 {bazi, ziwei, liuyao, ...}'),
    sa.Column('summary', sa.JSON(), nullable=True, comment='综合运势摘要（预留 AI 生成）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间戳（合规：删除走软删，物理删除仅 GDPR 显式请求）'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='关联用户 ID（唯一，实现一对一）'),
    sa.Column('birth', sa.Text(), nullable=True, comment='出生信息聚合 JSON（加密存储：date/time/gender/lunarYear/lunarMonth/lunarDay/province/city/lat/lng）'),
    sa.Column('timezone', sa.String(length=32), nullable=True, comment='时区'),
    sa.Column('theme', sa.String(length=16), nullable=True, comment='主题偏好'),
    sa.Column('notes', sa.Text(), nullable=True, comment='用户备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_deleted_at'))

    op.drop_table('reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('user_stash', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stash_owner_key'))

    op.drop_table('user_stash')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shares_user_id'))
        batch_op.drop_index(batch_op.f('ix_shares_module'))

    op.drop_table('shares')
    op.drop_table('schema_migrations')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
